config/routes.rb
Yogalife::Application.routes.draw do

devise_for :yogas, :controllers => { :omniauth_callbacks => "yogas/omniauth_callbacks" }

get 'sort_by(/:id)', :controller => 'events',  :action => 'sort_by'
get 'category(/:id)', :controller => 'events',  :action => 'category'

get "log_out" => "sessions#destroy", :as => "log_out"

get 'admin/login', :controller => 'admin',  :action => 'show'
post '/admin', :controller => 'admin',  :action => 'admin'

  resources :subscribers

  resources :manage_articles

  resources :cms

  mount Ckeditor::Engine => '/ckeditor'
  get "green/index"
  get "green/living_green"
  get "green/planet_earth"

  get "retreat/index"
  get "retreat/international"
  get "retreat/local"

  get "glow/index"
  get "glow/reviews"
  get "glow/haircare"
  get "glow/skincare"

  get "heal/index"
  get "heal/spirit"
  get "heal/mind"
  get "heal/body"

  get "nourish/index"
  get "nourish/restaurants_and_cafes"
  get "nourish/recipes"
  get "nourish/nutrition"

  get "pose/index"
  get "pose/pranayama"
  get "pose/community"
  get "pose/asanas_and_sequences"
  get "pose/pilates"
  get "pose/yoga"

  get "search_results/index"
  get "search_results/searchbox"

  get "home/index"

  get "/mag" => 'home#mag'
  get "/contact" => 'home#contact'
  get "/events" => 'home#events'
  get "/directory" => 'home#directory'
  get "/horos" => 'home#horos'
  get "/news" => 'home#news'
  get "/viewnews/:id" => 'home#viewnews'
  get "/about" => 'home#about'
  get "/team" => 'home#team'
  get "/where_to_buy" => 'home#where_to_buy'
  get "/article" => 'home#article'

get 'viewnews(/:id)', :controller => 'home',  :action => 'viewnews'

get 'eventdetail(/:id)', :controller => 'home',  :action => 'eventdetail'
get 'events(/:id)', :controller => 'home',  :action => 'event'

get 'viewpose(/:id)', :controller => 'home',  :action => 'viewpose'
get 'viewnourish(/:id)', :controller => 'home',  :action => 'viewnourish'
get 'viewheal(/:id)', :controller => 'home',  :action => 'viewheal'
get 'viewglow(/:id)', :controller => 'home',  :action => 'viewglow'
get 'viewretreat(/:id)', :controller => 'home',  :action => 'viewretreat'
get 'viewgreen(/:id)', :controller => 'home',  :action => 'viewgreen'
get 'viewmagazine(/:id)', :controller => 'home',  :action => 'viewmagazine'
get 'viewarticle(/:id)', :controller => 'home',  :action => 'viewarticle'

  resources :magazines

  resources :manage_follow_us

  resources :manage_advertisements

  resources :manage_greens

  resources :manage_retreats

  resources :manage_glows

  resources :manage_nourishes

  resources :manage_heals

  resources :manage_directories

  resources :banners

  resources :manage_teams

  resources :manage_events

  resources :manage_poses

  resources :manage_news

  resources :horoscopes

  resources :cities

  resources :countries

  resources :wheretobuys

  resources :subcategories

  resources :admin

  resource :admin

  resources :home

  root "home#index"

end

app/models/cm.rb
class Cm < ActiveRecord::Base
end

app/controllers/cms_controller.rb
class CmsController < ApplicationController
  before_action :set_cm, only: [:show, :edit, :update, :destroy]

  # GET /cms
  # GET /cms.json
  def index
    @cms = Cm.all
  end

  # GET /cms/1
  # GET /cms/1.json
  def show
  end

  # GET /cms/new
  def new
    @cm = Cm.new
  end

  # GET /cms/1/edit
  def edit
  end

  # POST /cms
  # POST /cms.json
  def create
    @cm = Cm.new(cm_params)

    respond_to do |format|
      if @cm.save
        format.html { redirect_to @cm, notice: 'Cm was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cm }
      else
        format.html { render action: 'new' }
        format.json { render json: @cm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cms/1
  # PATCH/PUT /cms/1.json
  def update
    respond_to do |format|
      if @cm.update(cm_params)
        format.html { redirect_to @cm, notice: 'Cm was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cms/1
  # DELETE /cms/1.json
  def destroy
    @cm.destroy
    respond_to do |format|
      format.html { redirect_to cms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cm
      @cm = Cm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cm_params
      params.require(:cm).permit(:page_title, :meta_keywords, :meta_desc, :page_content)
    end
end

app/helpers/cms_helper.rb
module CmsHelper
end

app/views/cms/_form.html.erb
<%= form_for(@cm) do |f| %>
  <% if @cm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cm.errors.count, "error") %> prohibited this cm from being saved:</h2>

      <ul>
      <% @cm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="adminform">
  <div class="left">



  <div class="label">
    <%= f.label :page_title, 'Page Title:*' %>
  </div>
    <%= f.text_field :page_title %>
  <div class="clr"></div><br/>

  <div class="label">
    <%= f.label :meta_keywords, 'Meta Keywords:*' %>
  </div>
    <%= f.text_field :meta_keywords %>
  <div class="clr"></div><br/>

  <div class="label">
    <%= f.label :meta_desc, 'Meta Description:*' %>
  </div>
    <%= f.text_field :meta_desc %>
  <div class="clr"></div><br/>

  <div class="label">
    <%= f.label :page_content, 'Page Content:*' %>
  </div>
  <div class="fld">
    <%= f.cktext_area :page_content %>
  </div>
  <div class="clr"></div><br/>

  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>

</div>  
<% end %>

app/views/cms/edit.html.erb
<div class="midRight">
<div class="rightMid">
    <div class="tableCon">
    	<div class="formHdBox">
        	<div class="tableHd">Admin Setting:  <span> </span>Edit CMS</div>
        </div>
<%= render 'form' %>

<%= link_to 'Show', @cm %> |
<%= link_to 'Back', cms_path %>
</div>
</div>
</div>

app/views/cms/index.html.erb
<div id="paged-data-container">
<div class="tableCon">
  <div class="formHdBox">
    <div class="tableHd">Admin Panel <span> Website Cms</span></div>
  </div>
  <div class="tabIner">
    <table cellpadding="0" cellspacing="0" width="100%" class="table">
      <tbody>
        <tr class="tableHdIner alt-row">
          <td width="28%" class="first">Page Title</td>
          <td width="8%">Meta Keyword</td>
          <td width="10%">Action</td>
        </tr>
        <% @cms.each do |cm| %>
          <tr class="tableDet">
            <td class="first"><%= cm.page_title %></td>
            <td><%= cm.meta_keywords %></td>
            <td> 
              <%= link_to image_tag("view.gif", :title => "View"), cm %>&nbsp;&nbsp;
              <%= link_to image_tag("edit.png", :title => "Edit"), edit_cm_path(cm) %>
            </td>
          </tr>
        <% end %>       
      </tbody>
    </table>
  </div>
</div>
</div>

<!-- <%= link_to 'Add CMS', new_cm_path %> -->

app/views/cms/new.html.erb
<div class="midRight">
<div class="rightMid">
    <div class="tableCon">
    	<div class="formHdBox">
        	<div class="tableHd">Admin Setting:  <span> </span>Add CMS</div>
        </div>
		<%= render 'form' %>
		<%= link_to 'Back', cms_path %>
	</div>
</div>
</div>

app/views/cms/show.html.erb
<div id="paged-data-container">
	<div class="tableCon">
	  	<div class="formHdBox">
		    <div class="tableHd">Admin Setting:  <span> </span>View CMS</div>
  		</div>
	  	<div class="adminform">
			<div class="left">
				<div class="fldline">
					<div class="label"><b>Page Title:</b></div>
					<div class="fld"><%= @cm.page_title %></div>
					<div class="clr"></div>
				</div>

				<div class="fldline">
					<div class="label"><b>Page Content:</b></div>
					<div class="fld"><%= raw @cm.page_content %></div>
					<div class="clr"></div>
				</div>
			</div>
			<div class="clr"></div>
		</div>
	</div>
</div>
<%= link_to 'Edit', edit_cm_path(@cm) %> |
<%= link_to 'Back', cms_path %>