config/routes.rb
Yogalife::Application.routes.draw do

devise_for :yogas, :controllers => { :omniauth_callbacks => "yogas/omniauth_callbacks" }

get 'sort_by(/:id)', :controller => 'events',  :action => 'sort_by'
get 'category(/:id)', :controller => 'events',  :action => 'category'

get "log_out" => "sessions#destroy", :as => "log_out"

get 'admin/login', :controller => 'admin',  :action => 'show'
post '/admin', :controller => 'admin',  :action => 'admin'

  resources :subscribers

  resources :manage_articles

  resources :cms

  mount Ckeditor::Engine => '/ckeditor'
  get "green/index"
  get "green/living_green"
  get "green/planet_earth"

  get "retreat/index"
  get "retreat/international"
  get "retreat/local"

  get "glow/index"
  get "glow/reviews"
  get "glow/haircare"
  get "glow/skincare"

  get "heal/index"
  get "heal/spirit"
  get "heal/mind"
  get "heal/body"

  get "nourish/index"
  get "nourish/restaurants_and_cafes"
  get "nourish/recipes"
  get "nourish/nutrition"

  get "pose/index"
  get "pose/pranayama"
  get "pose/community"
  get "pose/asanas_and_sequences"
  get "pose/pilates"
  get "pose/yoga"

  get "search_results/index"
  get "search_results/searchbox"

  get "home/index"

  get "/mag" => 'home#mag'
  get "/contact" => 'home#contact'
  get "/events" => 'home#events'
  get "/directory" => 'home#directory'
  get "/horos" => 'home#horos'
  get "/news" => 'home#news'
  get "/viewnews/:id" => 'home#viewnews'
  get "/about" => 'home#about'
  get "/team" => 'home#team'
  get "/where_to_buy" => 'home#where_to_buy'
  get "/article" => 'home#article'

get 'viewnews(/:id)', :controller => 'home',  :action => 'viewnews'

get 'eventdetail(/:id)', :controller => 'home',  :action => 'eventdetail'
get 'events(/:id)', :controller => 'home',  :action => 'event'

get 'viewpose(/:id)', :controller => 'home',  :action => 'viewpose'
get 'viewnourish(/:id)', :controller => 'home',  :action => 'viewnourish'
get 'viewheal(/:id)', :controller => 'home',  :action => 'viewheal'
get 'viewglow(/:id)', :controller => 'home',  :action => 'viewglow'
get 'viewretreat(/:id)', :controller => 'home',  :action => 'viewretreat'
get 'viewgreen(/:id)', :controller => 'home',  :action => 'viewgreen'
get 'viewmagazine(/:id)', :controller => 'home',  :action => 'viewmagazine'
get 'viewarticle(/:id)', :controller => 'home',  :action => 'viewarticle'

  resources :magazines

  resources :manage_follow_us

  resources :manage_advertisements

  resources :manage_greens

  resources :manage_retreats

  resources :manage_glows

  resources :manage_nourishes

  resources :manage_heals

  resources :manage_directories

  resources :banners

  resources :manage_teams

  resources :manage_events

  resources :manage_poses

  resources :manage_news

  resources :horoscopes

  resources :cities

  resources :countries

  resources :wheretobuys

  resources :subcategories

  resources :admin

  resource :admin

  resources :home

  root "home#index"

end

app/models/horoscope.rb
class Horoscope < ActiveRecord::Base
	mount_uploader :logo, PictureUploader
	mount_uploader :background, PictureUploader

	# mount_uploader :desc, CkeditorPictureUploader, :mount_on => :data_file_name

	validates :title, presence: true
	validates :subtitle, presence: true
	# validates_uniqueness_of :title
end

app/controllers/horoscopes_controller.rb
class HoroscopesController < ApplicationController

  # http_basic_authenticate_with :name => "myfinance", :password => "credit123"

  before_action :set_horoscope, only: [:show, :edit, :update, :destroy]

  # GET /horoscopes
  # GET /horoscopes.json
  def index
    @horoscopes = Horoscope.all
  end

  # GET /horoscopes/1
  # GET /horoscopes/1.json
  def show
  end

  # GET /horoscopes/new
  def new
    @horoscope = Horoscope.new
  end

  # GET /horoscopes/1/edit
  def edit
  end

  # POST /horoscopes
  # POST /horoscopes.json
  def create
    @horoscope = Horoscope.new(horoscope_params)

    respond_to do |format|
      if @horoscope.save
        format.html { redirect_to @horoscope, notice: 'Horoscope was successfully created.' }
        format.json { render action: 'show', status: :created, location: @horoscope }
      else
        format.html { render action: 'new' }
        format.json { render json: @horoscope.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /horoscopes/1
  # PATCH/PUT /horoscopes/1.json
  def update
    respond_to do |format|
      if @horoscope.update(horoscope_params)
        format.html { redirect_to @horoscope, notice: 'Horoscope was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @horoscope.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /horoscopes/1
  # DELETE /horoscopes/1.json
  def destroy
    @horoscope.destroy
    respond_to do |format|
      format.html { redirect_to horoscopes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_horoscope
      @horoscope = Horoscope.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def horoscope_params
      params.require(:horoscope).permit(:title, :subtitle, :start_date, :end_date, :logo, :background, :desc)
    end
end

app/helpers/horoscopes_helper.rb
module HoroscopesHelper
end

app/views/horoscopes/_form.html.erb
<%= form_for(@horoscope) do |f| %>
  <% if @horoscope.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@horoscope.errors.count, "error") %> prohibited this horoscope from being saved:</h2>

      <ul>
      <% @horoscope.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="adminform">
  <div class="left">



  <div class="label">
    <%= f.label :title, 'Monthly Horoscopes Title' %>
  </div>
    <%= f.text_field :title %>
  <div class="clr"></div><br/>

  <div class="label">
    <%= f.label :subtitle, 'Monthly Horoscopes Subtitle' %>
  </div>
    <%= f.text_field :subtitle %>
  <div class="clr"></div><br/>

  <div class="label" id="datepicker" data-date="current">
    <%= f.label :start_date, 'Monthly Horoscopes Start Date' %>
  </div>
    <%= f.text_field :start_date, 'data-behaviour' => 'datepicker' %>
  <div class="clr"></div><br/>

  <div class="label" id="datepicker" data-date="current">
    <%= f.label :end_date, 'Monthly Horoscopes End Date' %>
  </div>
    <%= f.text_field :end_date, 'data-behaviour' => 'datepicker' %>
  <div class="clr"></div><br/>

  <div class="label">
    <%= f.label :logo, 'Monthly Horoscopes Logo' %>
  </div>
    <%= f.file_field :logo %>
  <div class="clr"></div><br/>

  <div class="label">
    <%= f.label :background, 'Monthly Horoscopes BG Image' %>
  </div>
    <%= f.file_field :background %>
  <div class="clr"></div><br/>

  <div class="label">
    <%= f.label :desc, 'Monthly Horoscopes Description' %>
  </div>
  <div class="fld">
    <%= f.cktext_area :desc %>
  </div>
  <div class="clr"></div><br/>

  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>


</div>


<% end %>

app/views/horoscopes/edit.html.erb
<div class="midRight">
<div class="rightMid">
    <div class="tableCon">
    	<div class="formHdBox">
        	<div class="tableHd">Admin Setting:  <span> </span>Edit Monthly Horoscopes</div>
        </div>
	<%= render 'form' %>
	<%= link_to 'Show', @horoscopes %> |
	<%= link_to 'Back', horoscopes_path %>
    </div>
</div>
</div>

app/views/horoscopes/index.html.erb
<div id="paged-data-container">
<div class="tableCon">
  <div class="formHdBox">
    <div class="tableHd">Monthly Horoscopes</div>
    <div class="selectCity"><img src="assets/addnew.png" border="0"><%= link_to 'Add Monthly Horoscopes', new_horoscope_path %>
    </div>
  </div>


<div class="paged-data">
    <div class="tabIner">

<table cellpadding="0" cellspacing="0" width="100%" class="table">
  <thead>
    <tr class="tableHdIner alt-row">
      <td width="5%" class="first">S. NO</td>
      <td width="10%">Title</td>
      <td width="10%">Logo Image</td>
      <td width="10%">Background Image</td>
      <td width="20%">Description</td>
      <td width="10%">Start Date</td>
      <td width="10%">End Date</td>
      <td width="12%">Action</td>
    </tr>
  </thead>

  <tbody>
    <% i = 0 %>
    <% @horoscopes.each do |horoscope| %>
      <tr class="tableDet">
        <td class="first"><%= i = i + 1 %></td>
        <td><%= horoscope.title.truncate(40) %></td>
        <td><%= image_tag(horoscope.logo_url, :width => 25) if horoscope.logo.present? %></td>
        <td><%= image_tag(horoscope.background_url, :width => 25) if horoscope.background.present? %></td>
        <td><%= raw horoscope.desc.truncate(140) %></td>
        <td><%= horoscope.start_date.strftime('%d-%b-%Y') %></td>
        <td><%= horoscope.end_date.strftime('%d-%b-%Y') %></td>
        <td align="center">
          <%= link_to image_tag("view.gif", :title => "View"), horoscope %>&nbsp;&nbsp;
          <%= link_to image_tag("edit.png", :title => "Edit"), edit_horoscope_path(horoscope) %>&nbsp;&nbsp;
          <%= link_to image_tag("delete.png", :title => "Delete"), horoscope, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
</div>
</div>
</div>

app/views/horoscopes/new.html.erb
<div class="midRight">
<div class="rightMid">
    <div class="tableCon">
    	<div class="formHdBox">
        	<div class="tableHd">Admin Setting:  <span> </span>Add Monthly Horoscopes</div>
        </div>
		<%= render 'form' %>
		<%= link_to 'Back', horoscopes_path %>
	</div>
</div>
</div>

app/views/horoscopes/show.html.erb
<div id="paged-data-container">
  <div class="tableCon">
      <div class="formHdBox">
        <div class="tableHd">Admin Setting:  <span> </span>View Monthly Horoscopes</div>
      </div>
      <div class="adminform">
        <div class="left">

          <div class="fldline">
            <div class="label"><b>Title:</b></div>
            <div class="fld"><%= @horoscope.title %></div>
            <div class="clr"></div>
          </div>

          <div class="fldline">
            <div class="label"><b>SubTitle:</b></div>
            <div class="fld"><%= @horoscope.subtitle %></div>
            <div class="clr"></div>
          </div>

          <div class="fldline">
            <div class="label"><b>Start Date:</b></div>
            <div class="fld"><%= @horoscope.start_date %></div>
            <div class="clr"></div>
          </div>

          <div class="fldline">
            <div class="label"><b>End Date:</b></div>
            <div class="fld"><%= @horoscope.end_date %></div>
            <div class="clr"></div>
          </div>

          <div class="fldline">
            <div class="label"><b>Logo:</b></div>
            <div class="fld"><%= image_tag(@horoscope.logo_url, :width => 300) if @horoscope.logo.present? %></div>
            <div class="clr"></div>
          </div>

          <div class="fldline">
            <div class="label"><b>Background Image:</b></div>
            <div class="fld"><%= image_tag(@horoscope.background_url, :width => 300) if @horoscope.background.present? %></div>
            <div class="clr"></div>
          </div>

          <div class="fldline">
            <div class="label"><b>Description:</b></div>
            <div class="fld"><%= raw @horoscope.desc %></div>
            <div class="clr"></div>
          </div>

        </div>

        <div class="clr"></div>
      </div>

  </div>
</div>

<%= link_to 'Edit', edit_horoscope_path(@horoscope) %> |
<%= link_to 'Back', horoscopes_path %>