config/routes.rb
Yogalife::Application.routes.draw do

devise_for :yogas, :controllers => { :omniauth_callbacks => "yogas/omniauth_callbacks" }

get 'sort_by(/:id)', :controller => 'events',  :action => 'sort_by'
get 'category(/:id)', :controller => 'events',  :action => 'category'

get "log_out" => "sessions#destroy", :as => "log_out"

get 'admin/login', :controller => 'admin',  :action => 'show'
post '/admin', :controller => 'admin',  :action => 'admin'

  resources :subscribers

  resources :manage_articles

  resources :cms

  mount Ckeditor::Engine => '/ckeditor'
  get "green/index"
  get "green/living_green"
  get "green/planet_earth"

  get "retreat/index"
  get "retreat/international"
  get "retreat/local"

  get "glow/index"
  get "glow/reviews"
  get "glow/haircare"
  get "glow/skincare"

  get "heal/index"
  get "heal/spirit"
  get "heal/mind"
  get "heal/body"

  get "nourish/index"
  get "nourish/restaurants_and_cafes"
  get "nourish/recipes"
  get "nourish/nutrition"

  get "pose/index"
  get "pose/pranayama"
  get "pose/community"
  get "pose/asanas_and_sequences"
  get "pose/pilates"
  get "pose/yoga"

  get "search_results/index"
  get "search_results/searchbox"

  get "home/index"

  get "/mag" => 'home#mag'
  get "/contact" => 'home#contact'
  get "/events" => 'home#events'
  get "/directory" => 'home#directory'
  get "/horos" => 'home#horos'
  get "/news" => 'home#news'
  get "/viewnews/:id" => 'home#viewnews'
  get "/about" => 'home#about'
  get "/team" => 'home#team'
  get "/where_to_buy" => 'home#where_to_buy'
  get "/article" => 'home#article'

get 'viewnews(/:id)', :controller => 'home',  :action => 'viewnews'

get 'eventdetail(/:id)', :controller => 'home',  :action => 'eventdetail'
get 'events(/:id)', :controller => 'home',  :action => 'event'

get 'viewpose(/:id)', :controller => 'home',  :action => 'viewpose'
get 'viewnourish(/:id)', :controller => 'home',  :action => 'viewnourish'
get 'viewheal(/:id)', :controller => 'home',  :action => 'viewheal'
get 'viewglow(/:id)', :controller => 'home',  :action => 'viewglow'
get 'viewretreat(/:id)', :controller => 'home',  :action => 'viewretreat'
get 'viewgreen(/:id)', :controller => 'home',  :action => 'viewgreen'
get 'viewmagazine(/:id)', :controller => 'home',  :action => 'viewmagazine'
get 'viewarticle(/:id)', :controller => 'home',  :action => 'viewarticle'

  resources :magazines

  resources :manage_follow_us

  resources :manage_advertisements

  resources :manage_greens

  resources :manage_retreats

  resources :manage_glows

  resources :manage_nourishes

  resources :manage_heals

  resources :manage_directories

  resources :banners

  resources :manage_teams

  resources :manage_events

  resources :manage_poses

  resources :manage_news

  resources :horoscopes

  resources :cities

  resources :countries

  resources :wheretobuys

  resources :subcategories

  resources :admin

  resource :admin

  resources :home

  root "home#index"

end

app/models/manage_nourish.rb
class ManageNourish < ActiveRecord::Base
	mount_uploader :image, PictureUploader

	def should_generate_new_friendly_id?
  		slug.blank? || title_changed?
	end

	extend FriendlyId
  		friendly_id :title, use: :slugged
end

app/controllers/manage_nourishes_controller.rb
class ManageNourishesController < ApplicationController
  before_action :set_manage_nourish, only: [:show, :edit, :update, :destroy]

  # GET /manage_nourishes
  # GET /manage_nourishes.json
  def index
    @manage_nourishes = ManageNourish.all
  end

  # GET /manage_nourishes/1
  # GET /manage_nourishes/1.json
  def show
  end

  # GET /manage_nourishes/new
  def new
    @manage_nourish = ManageNourish.new
  end

  # GET /manage_nourishes/1/edit
  def edit
  end

  # POST /manage_nourishes
  # POST /manage_nourishes.json
  def create
    @manage_nourish = ManageNourish.new(manage_nourish_params)

    respond_to do |format|
      if @manage_nourish.save
        format.html { redirect_to @manage_nourish, notice: 'Manage nourish was successfully created.' }
        format.json { render action: 'show', status: :created, location: @manage_nourish }
      else
        format.html { render action: 'new' }
        format.json { render json: @manage_nourish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manage_nourishes/1
  # PATCH/PUT /manage_nourishes/1.json
  def update
    respond_to do |format|
      if @manage_nourish.update(manage_nourish_params)
        format.html { redirect_to @manage_nourish, notice: 'Manage nourish was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @manage_nourish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manage_nourishes/1
  # DELETE /manage_nourishes/1.json
  def destroy
    @manage_nourish.destroy
    respond_to do |format|
      format.html { redirect_to manage_nourishes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manage_nourish
      @manage_nourish = ManageNourish.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manage_nourish_params
      params.require(:manage_nourish).permit(:title, :sub_category, :image, :created_by, :website, :desc)
    end
end

app/helpers/manage_nourishes_helper.rb
module ManageNourishesHelper
end

app/views/manage_nourishes/_form.html.erb
<%= form_for(@manage_nourish) do |f| %>
  <% if @manage_nourish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manage_nourish.errors.count, "error") %> prohibited this manage_nourish from being saved:</h2>

      <ul>
      <% @manage_nourish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="adminform">
  <div class="left">


  <div class="label">
    <%= f.label :title, 'Nourish Title' %>
  </div>
    <%= f.text_field :title %>
  <div class="clr"></div><br/>

  <div class="label">
    <%= f.label :sub_category, 'Nourish Sub Category' %>
  </div>
    <%= f.collection_select :sub_category, Subcategory.all,  :sub_cat_name, :sub_cat_name , :prompt=>'Select Subategory*'%>
  <div class="clr"></div><br/>

  <div class="label">
    <%= f.label :image %>
  </div>
    <%= f.file_field :image %>
  <div class="clr"></div><br/>

  <div class="label">
    <%= f.label :created_by, 'Created By' %>
  </div>
    <%= f.text_field :created_by %>
  <div class="clr"></div><br/>

  <div class="label">
    <%= f.label :website %>
  </div>
    <%= f.text_field :website %>
  <div class="clr"></div><br/>

  <div class="label">
    <%= f.label :desc, 'Description' %>
  </div>
  <div class="fld">
    <%= f.cktext_area :desc %>
  </div>
  <div class="clr"></div><br/>

  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>

</div>
<% end %>

app/views/manage_nourishes/edit.html.erb
<div class="midRight">
<div class="rightMid">
    <div class="tableCon">
    	<div class="formHdBox">
        	<div class="tableHd">Admin Setting:  <span> </span>Edit Nourish</div>
        </div>
<%= render 'form' %>

<%= link_to 'Show', @manage_nourish %> |
<%= link_to 'Back', manage_nourishes_path %>
</div>
</div>
</div>

app/views/manage_nourishes/index.html.erb
<div id="paged-data-container">
<div class="tableCon">
  <div class="formHdBox">
    <div class="tableHd">Nourish</div>
    <div class="selectCity"><img src="assets/addnew.png" border="0"><%= link_to 'Add Nourish', new_manage_nourish_path %>
    </div>
  </div>
  <div class="paged-data">
    <div class="tabIner">
      <table cellpadding="0" cellspacing="0" width="100%" class="table">
        <thead>
          <tr class="tableHdIner alt-row">
              <td width="5%" class="first">S. NO</td>
              <td width="15%">Nourish Title</td>
              <td width="10%">Nourish Image</td>
              <td width="20%">Description</td>
              <td width="10%">Created By</td>
              <td width="10%">Created</td>
              <td width="10%">Updated</td> 
              <td width="12%">Action</td>
          </tr>
        </thead>
        <tbody>
          <% i = 0 %>
          <% @manage_nourishes.each do |manage_nourish| %>
            <tr class="tableDet">
                <td class="first"><%= i = i + 1 %></td>
                <td><%= manage_nourish.title.truncate(40) %></td>
                <td><%= image_tag(manage_nourish.image, :height => 25, :width => 25) if manage_nourish.image.present? %></td>
                <td><%= raw manage_nourish.desc.truncate(140) %></td>
                <td><%= manage_nourish.created_by %></td>
                <td><%= manage_nourish.created_at.strftime('%d-%b-%Y') %></td>
                <td><%= manage_nourish.updated_at.strftime('%d-%b-%Y') %></td>
                <td align="center">
                  <%= link_to image_tag("view.gif", :title => "View"), manage_nourish %>&nbsp;&nbsp;
                  <%= link_to image_tag("edit.png", :title => "Edit"), edit_manage_nourish_path(manage_nourish) %>&nbsp;&nbsp;
                  <%= link_to image_tag("delete.png", :title => "Delete"), manage_nourish, method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
            </tr>

          <% end %>
        </tbody>
      </table>  
    </div>
  </div>
</div>
</div>

app/views/manage_nourishes/new.html.erb
<div class="midRight">
<div class="rightMid">
    <div class="tableCon">
    	<div class="formHdBox">
        	<div class="tableHd">Admin Setting:  <span> </span>Add Nourish</div>
        </div>
<%= render 'form' %>

<%= link_to 'Back', manage_nourishes_path %>
</div>
</div>
</div>

app/views/manage_nourishes/show.html.erb
<div id="paged-data-container">
  <div class="tableCon">
      <div class="formHdBox">
        <div class="tableHd">Admin Setting:  <span> </span>View Nourish</div>
      </div>
      <div class="adminform">
      <div class="left">

        <div class="fldline">
          <div class="label"><b>Title:</b></div>
          <div class="fld"><%= @manage_nourish.title %></div>
          <div class="clr"></div>
        </div>
        
        <div class="fldline">
          <div class="label"><b>Sub Category:</b></div>
          <div class="fld"><%= @manage_nourish.sub_category %></div>
          <div class="clr"></div>
        </div>

        <div class="fldline">
          <div class="label"><b>Created By:</b></div>
          <div class="fld"><%= @manage_nourish.created_by %></div>
          <div class="clr"></div>
        </div>

        <div class="fldline">
          <div class="label"><b>Website:</b></div>
          <div class="fld"><%= @manage_nourish.website %></div>
          <div class="clr"></div>
        </div>

        <div class="fldline">
          <div class="label"><b>Image:</b></div>
          <div class="fld"><%= image_tag(@manage_nourish.image, :width => 300) if @manage_nourish.image.present? %></div>
          <div class="clr"></div>
        </div>

        <div class="fldline">
          <div class="label"><b>Description:</b></div>
          <div class="fld"><%= raw @manage_nourish.desc %></div>
          <div class="clr"></div>
        </div>
                          
      </div>
      
      <div class="clr"></div>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_manage_nourish_path(@manage_nourish) %> |
<%= link_to 'Back', manage_nourishes_path %>